<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Kwad">

<!-- ======================================================== -->	
	<xacro:include filename="$(find robotuna_ekf_simulator)/urdf/material.xacro" />
	<xacro:include filename="$(find robotuna_ekf_simulator)/urdf/macros.xacro"/>
	<xacro:include filename="$(find robotuna_ekf_simulator)/urdf/Kwad.gazebo" />
<!-- ======================================================== -->	
	<!-- Constants -->
	<xacro:property name="pi_value" value="3.14159263" />

	<!-- Dimensions for cross beam arms -->
	<xacro:property name="width" value="0.0315" /> 
	<xacro:property name="length" value="0.45" />
	<xacro:property name="height" value="0.015" />
	<!-- Mass of cross beam arms -->
	<xacro:property name="mass_fr" value="0.8" />

	<!-- Dimension of propellers -->
	<xacro:property name="radiusp" value="0.20" />
	<!-- Mass of propellers -->
	<xacro:property name="mass_pr" value="0.0055" />
	<!-- Location of propellers -->
	<xacro:property name="prop_loc" value="0.15909" />

<!-- ======================================================== -->
<!-- ======================================================== -->
<!-- ####################### -->
		<!-- Links -->
<!-- ####################### -->

	<!-- Base link -->
	<link name="base_link"/>

<!-- ======================================================== -->
<!-- Quadcopter frame links -->
	<!-- First arm -->
	<xacro:boxLink 
		name="arm_1"
		mass="${mass_fr}"
		x_dim="${width}" y_dim="${length}" z_dim="${height}"
		y="${pi_value/4}"
		color="red" 
	/>

	<!-- Second arm -->
	<xacro:boxLink 
		name="arm_2"
		mass="${mass_fr}"
		x_dim="${width}" y_dim="${length}" z_dim="${height}"
		y="${-pi_value/4}"
		color="white" 
	/>

	<!-- Electronics mounting plate -->
	<xacro:boxLink 
		name="plate1"
		mass="0.01"
		x_dim="0.12" y_dim="0.12" z_dim="0.01"
		color="black" 
	/>
<!-- ======================================================== -->
<!-- Motor links -->
	<!-- Front right motor -->
	<xacro:cylinderLink
		name="cyl_fr"
		mass="0.01"
		radius="0.016"
		height="0.02"
		color="golden"
	/>

	<!-- Back left motor -->
	<xacro:cylinderLink
		name="cyl_bl"
		mass="0.01"
		radius="0.016"
		height="0.02"
		color="golden"
	/>

	<!-- Front left motor -->
	<xacro:cylinderLink
		name="cyl_fl"
		mass="0.01"
		radius="0.016"
		height="0.02"
		color="golden"
	/>

	<!-- Back right motor -->
	<xacro:cylinderLink
		name="cyl_br"
		mass="0.01"
		radius="0.016"
		height="0.02"
		color="golden"
	/>

<!-- ======================================================== -->
<!-- Propeller links -->
	<!-- Propellers of the quad: fr, fl, br, bl -->
	<!-- For the propellers we don't use the boxLink macros, because we need to make their
		 inertials "flat" (no inertia around x or y axis). Thus we construct them the
		 traditional way. -->

	<xacro:boxLink_customInertia
		name="prop_front_right"
		mass="${mass_pr}"
		x_dim="${0.03302/3}" y_dim="${radiusp*0.8}" z_dim="0.005"
		ix="0" iy="0" iz="${4.42448e-5}"
		color="black" 
	/>

	<xacro:boxLink_customInertia
		name="prop_front_left"
		mass="${mass_pr}"
		x_dim="${0.03302/3}" y_dim="${radiusp*0.8}" z_dim="0.005"
		ix="0" iy="0" iz="${4.42448e-5}"
		color="black" 
	/>

	<xacro:boxLink_customInertia
		name="prop_back_right"
		mass="${mass_pr}"
		x_dim="${0.03302/3}" y_dim="${radiusp*0.8}" z_dim="0.005"
		ix="0" iy="0" iz="${4.42448e-5}"
		color="black" 
	/>

	<xacro:boxLink_customInertia
		name="prop_back_left"
		mass="${mass_pr}"
		x_dim="${0.03302/3}" y_dim="${radiusp*0.8}" z_dim="0.005"
		ix="0" iy="0" iz="${4.42448e-5}"
		color="black" 
	/>
<!-- ======================================================== -->
<!-- Sensor links -->
	<!-- Camera -->
	<xacro:boxLink 
		name="camera_link"
		mass="${1e-5}"
		x_dim="0.01" y_dim="0.01" z_dim="0.01"
		color="red"
	/>

	<!-- IMU -->
	<xacro:boxLink 
		name="imu_link"
		mass="${1e-5}"
		x_dim="0.01" y_dim="0.01" z_dim="0.01"
		color="red"
	/>
<!-- ======================================================== -->
<!-- ======================================================== -->

<!-- ####################### -->
		<!-- Joints -->
<!-- ####################### -->

	<joint name="base_joint" type="fixed">
		<parent link="base_link" />
		<child link="arm_1" />
		<origin xyz="0 0 0" rpy="0 0 0" />
  	</joint>

	<!-- Define the joint between the arms of the frame -->
	<joint name="center" type="fixed">
		<parent link="arm_1" />
		<child link="arm_2" />
		
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
	<!-- Define joint between prop fr and frame -->
	<joint name="joint_front_right_prop" type="continuous">
		<parent link="arm_2" />
		<child link="prop_front_right" />
		<origin xyz="${prop_loc - 0.01} ${prop_loc - 0.01} 0.021" rpy="0 0 0"/>
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
	<!-- Define joint between prop fl and frame -->
	<joint name="joint_front_left_prop" type="continuous">
		<parent link="arm_1" />
		<child link="prop_front_left" />
		<origin xyz="${-prop_loc + 0.01} ${prop_loc - 0.01} 0.021" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between prop br and frame -->
	<joint name="joint_back_right_prop" type="continuous">
		<parent link="arm_1" />
		<child link="prop_back_right" />
		<origin xyz="${prop_loc - 0.01} ${-prop_loc + 0.01} 0.021" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between prop br and frame -->
	<joint name="joint_back_left_prop" type="continuous">
		<parent link="arm_2" />
		<child link="prop_back_left" />
		<origin xyz="${-prop_loc + 0.01} ${-prop_loc + 0.01} 0.021" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between plate1 and frame -->
	<joint name="joint_plate1_frame" type="fixed">
		<parent link="arm_2" />
		<child link="plate1" />
		<origin xyz="${0} ${0} 0.005" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between cyl_fr and frame -->
	<joint name="joint_cyl_fr_frame" type="fixed">
		<parent link="arm_2" />
		<child link="cyl_fr" />
		<origin xyz="${prop_loc - 0.01} ${prop_loc - 0.01} 0.01" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between cyl_bl and frame -->
	<joint name="joint_cyl_bl_frame" type="fixed">
		<parent link="arm_2" />
		<child link="cyl_bl" />
		<origin xyz="${-prop_loc + 0.01} ${-prop_loc + 0.01} 0.01" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between cyl_fl and frame -->
	<joint name="joint_cyl_fl_frame" type="fixed">
		<parent link="arm_1" />
		<child link="cyl_fl" />
		<origin xyz="${-prop_loc + 0.01} ${prop_loc - 0.01} 0.01" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between cyl_br and frame -->
	<joint name="joint_cyl_br_frame" type="fixed">
		<parent link="arm_1" />
		<child link="cyl_br" />
		<origin xyz="${prop_loc - 0.01} ${-prop_loc + 0.01} 0.01" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between camera and frame -->
	<joint name="joint_camera_frame" type="fixed">
		<parent link="plate1" />
		<child link="camera_link" />
		<origin xyz="${0} ${0.06} 0.005" rpy="0 0.1 ${3.14/2}" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
	<!-- Define joint between camera and frame -->
	<joint name="joint_imu_frame" type="fixed">
		<parent link="plate1" />
		<child link="imu_link" />
		<origin xyz="0 0 0" rpy="0 0 0" />
	</joint>
<!-- ======================================================== -->
<!-- ======================================================== -->

<!-- ####################### -->
	<!-- Transmissions -->
<!-- ####################### -->

<!-- Add transmission elements -->
	<transmission name="front_right_motor_joint" >
		<type>transmission_interface/SimpleTransmission</type>	
		<joint name="joint_front_right_prop">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="BLDC_motor1">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	
	<transmission name="front_left_motor_joint" >
		<type>transmission_interface/SimpleTransmission</type>	
		<joint name="joint_front_left_prop">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="BLDC_motor2">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	
	<transmission name="back_right_motor_joint" >
		<type>transmission_interface/SimpleTransmission</type>	
		<joint name="joint_back_right_prop">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="BLDC_motor3">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	
	<transmission name="back_left_motor_joint" >
		<type>transmission_interface/SimpleTransmission</type>	
		<joint name="joint_back_left_prop">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="BLDC_motor4">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

</robot>
